# Generated by Django 3.1.1 on 2020-09-21 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, max_length=516, null=True)),
                ('cards', models.CharField(choices=[('1', '1,2,3,5,8,13,20,40,100'), ('2', '1,2,3,5,8,13,20,40,?'), ('3', '0,1,2,4,8,16,32,64'), ('4', '1,2,4,8,12,16,24,40,80'), ('5', '☕,1,2,3,5,8,13,20,?'), ('6', 'XS,S,M,L,XL,XXL,?'), ('7', '1,2,5,10,20,50,100'), ('8', '1,2,3,4,5')], default='1', max_length=1)),
                ('access', models.CharField(choices=[('PU', 'Public'), ('PR', 'Private')], default='PU', max_length=2)),
                ('access_code', models.CharField(blank=True, max_length=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_value', models.CharField(max_length=3)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
